[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/unite-outline'
depends = ['unite']

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-surround'

# colorscheme 
[[plugins]]
repo = 'nanotech/jellybeans.vim'

# quick 
[[plugins]]
repo = 'thinca/vim-quickrun'

# syntacs
[[plugins]]
repo = 'scrooloose/syntastic'

# accelerate j k
[[plugins]]
repo = 'rhysd/accelerated-jk'

[[plugins]]
repo = 'soramugi/auto-ctags.vim'

# indent
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# memo
[[plugins]]
repo = 'glidenote/memolist.vim'

# browser
[[plugins]]
repo = 'tyru/open-browser.vim'

