tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/php"
tap "sanemat/font"

brew "bash"
brew "composer"
brew "fontforge", args: ["with-giflib", "with-libspiro"]
brew "go"
brew "hugo"
brew "jq"
brew "kubernetes-cli"
brew "lua"
brew "mysql"
brew "peco"
brew "pyenv"
brew "stern"
brew "tmux"
brew "tree"
brew "wget"
brew "zsh"
brew "goenv"

cask "caffeine"
cask "sequel-pro"
cask 'clipy'
